export const DECREASE="DECREASE"
export const INCREASE="INCREASE"
export const REMOVE="REMOVE"
export const CLEAR="CLEAR"
export const GET_TOTAL="GET_TOTAL"
export const TOGGLE_AMOUNT="TOGGLE_AMOUNT"
